# GitHub Pages 配置文件

# 站点设置
title: "个人网站"
description: "基于GitHub Pages的静态个人网站"
author: "Your Name"
email: "your.email@example.com"

# 网站URL（部署后会自动更新）
url: "https://yourusername.github.io"
baseurl: "/repository-name"  # 如果仓库名不是 username.github.io，需要设置这个

# 构建设置
markdown: kramdown
highlighter: rouge
theme: minima

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 排除文件
exclude:
  - README.md
  - .gitignore
  - .github/

# 包含文件
include:
  - _pages

# 集合
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext

# 默认设置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# 社交链接
social:
  github: yourusername
  twitter: yourusername
  linkedin: yourusername

# 导航
navigation:
  - title: "首页"
    url: "/"
  - title: "关于"
    url: "/about"
  - title: "项目"
    url: "/projects"
  - title: "博客"
    url: "/blog"
  - title: "联系"
    url: "/contact"

# SEO设置
seo:
  type: "Person"
  name: "Your Name"
  same_as:
    - "https://github.com/yourusername"
    - "https://linkedin.com/in/yourusername"
