# [Info]
site_name: Herohui's Site
site_url: https://Herohui04.github.io
site_author: xi-luhui

# [Theme Configuration]
theme:
  name: material
  features:
    - content.code.copy
  palette:
    # 日间模式
    - scheme: default
      primary: indigo # 主色
      accent: pink   # 强调色
      toggle:
        icon: material/weather-sunny
        name: 切换到夜间模式
    # 夜间模式
    - scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: 切换到日间模式

plugins:
  - search

  - tags


markdown_extensions:
  - pymdownx.highlight:
      # 显示行号
      linenums: true
      # 显示编程语言名称
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

